/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Window;

import Utilities.FileReader;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author Yasen
 */
public class HighScorePanel extends javax.swing.JPanel {
    FileReader scoreReader;
    MainWindow parent;
    JLabel[] names = new JLabel[5];
    JLabel[] scores = new JLabel[5];
    /**
     * Creates new form HighScorePanel
     */
    public HighScorePanel(MainWindow p) {
        initComponents();
        parent=p;
        scoreReader = new FileReader();
        
        names[0] = name5;
        names[1] = name4;
        names[2] = name3;
        names[3] = name2;
        names[4] = name1;
        
        scores[0] = score5;
        scores[1] = score4;
        scores[2] = score3;
        scores[3] = score2;
        scores[4] = score1;
        
        buildScoreBoard();
    }
    
    void buildScoreBoard(){
        ArrayList<String> data = scoreReader.printMap();        
        for(int i = 0; i < 5; i++){
            names[i].setText(data.get(i).split(":")[0]);
            scores[i].setText(data.get(i).split(":")[1]);
        }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        name5 = new javax.swing.JLabel();
        score1 = new javax.swing.JLabel();
        score2 = new javax.swing.JLabel();
        score3 = new javax.swing.JLabel();
        score4 = new javax.swing.JLabel();
        score5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel3.setText("3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("5");

        name1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        name1.setText("jLabel6");

        name2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        name2.setText("jLabel7");

        name3.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        name3.setText("jLabel8");

        name4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        name4.setText("jLabel9");

        name5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        name5.setText("jLabel10");

        score1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        score1.setText("jLabel11");

        score2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        score2.setText("jLabel12");

        score3.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        score3.setText("jLabel13");

        score4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        score4.setText("jLabel14");

        score5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        score5.setText("jLabel15");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name5)
                                    .addComponent(name4)
                                    .addComponent(name1)
                                    .addComponent(name2)
                                    .addComponent(name3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(score1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(score2)
                            .addComponent(score3)
                            .addComponent(score4)
                            .addComponent(score5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name1)
                    .addComponent(score1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name2)
                    .addComponent(score2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(name3)
                    .addComponent(score3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(name4)
                    .addComponent(score4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(name5)
                    .addComponent(score5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       parent.pauseGame();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel score1;
    private javax.swing.JLabel score2;
    private javax.swing.JLabel score3;
    private javax.swing.JLabel score4;
    private javax.swing.JLabel score5;
    // End of variables declaration//GEN-END:variables
}
