package Window;

import Utilities.FileWriter;
import Utilities.MazeKeyListener;
import java.awt.event.KeyEvent;

/**
 *
 * @author Nels
 */
public class MenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuPanel
     */
    MainWindow parent;
        
    public MenuPanel(MainWindow p)  {
        initComponents();
        MazeKeyListener listener = new MazeKeyListener(this);
        this.addKeyListener(listener);
        this.setFocusable(true);
        
        activeGame(false);
        parent = p;        
        //parent.setContentPane(this);
        
        if (System.getProperty("os.name").equals("Mac OS X")) {
            fullScreenButton.setVisible(false);
        }
    }
    
    public void activeGame(boolean active){
         continueGame.setVisible(active);
         saveGame.setVisible(active);
    }
    
     public void updateGame(KeyEvent e) {
        keyInput(e.getKeyCode());
    }
    
    public void keyInput(int key) {
        switch (key) {
            case KeyEvent.VK_ESCAPE:
                parent.unPauseGame();
                break;
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fullScreenButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        continueGame = new javax.swing.JButton();
        loadGameButton = new javax.swing.JButton();
        saveGame = new javax.swing.JButton();
        highScoreButton = new javax.swing.JButton();
        optionsButtons = new javax.swing.JButton();
        exitButton2 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        fullScreenButton.setText("Fullscreen");
        fullScreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullScreenButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 123.0;
        gridBagConstraints.weighty = 123.0;
        gridBagConstraints.insets = new java.awt.Insets(29, 19, 19, 19);
        add(fullScreenButton, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        startButton.setText("New Game");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jPanel1.add(startButton);

        continueGame.setText("Continue");
        continueGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueGameActionPerformed(evt);
            }
        });
        jPanel1.add(continueGame);

        loadGameButton.setText("Load Game");
        loadGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGameButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loadGameButton);

        saveGame.setText("Save Game");
        saveGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGameActionPerformed(evt);
            }
        });
        jPanel1.add(saveGame);

        highScoreButton.setText("High Scores");
        highScoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highScoreButtonActionPerformed(evt);
            }
        });
        jPanel1.add(highScoreButton);

        optionsButtons.setText("Options");
        optionsButtons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsButtonsActionPerformed(evt);
            }
        });
        jPanel1.add(optionsButtons);

        exitButton2.setText("Exit");
        exitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 180;
        gridBagConstraints.ipady = 100;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void fullScreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullScreenButtonActionPerformed
        MainWindow.mazeWindow.toggleFullscreen();
    }//GEN-LAST:event_fullScreenButtonActionPerformed

    private void optionsButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsButtonsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionsButtonsActionPerformed

    private void highScoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highScoreButtonActionPerformed
        parent.showHighScores();        // TODO add your handling code here:
    }//GEN-LAST:event_highScoreButtonActionPerformed

    private void continueGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueGameActionPerformed
       parent.unPauseGame();
    }//GEN-LAST:event_continueGameActionPerformed

    private void exitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton2ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_exitButton2ActionPerformed

    private void saveGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGameActionPerformed
        parent.saveGame();
    }//GEN-LAST:event_saveGameActionPerformed

    private void loadGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGameButtonActionPerformed
        parent.loadGame();        // TODO add your handling code here:
        
        activeGame(true);
    }//GEN-LAST:event_loadGameButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        parent.startGame();
        activeGame(true);
        continueGame.setVisible(true);
        saveGame.setVisible(true);

        //      MainWindow.mazeWindow.setContentPane(MainWindow.mazeWindow.game);
        // MainWindow.mazeWindow.setVisible(true);
    }//GEN-LAST:event_startButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continueGame;
    private javax.swing.JButton exitButton2;
    private javax.swing.JButton fullScreenButton;
    private javax.swing.JButton highScoreButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loadGameButton;
    private javax.swing.JButton optionsButtons;
    private javax.swing.JButton saveGame;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
