package Window;

/**
 *
 * @author Nels
 */
public class OptionPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuPanel
     */
    MainWindow parent;
    public boolean activeGame = false;

    public OptionPanel(MainWindow p) {
        initComponents();

        this.setFocusable(true);
        parent = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jToggleButton1 = new javax.swing.JToggleButton();
        mainMenuBackground = new javax.swing.JLabel();

        setLayout(null);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(400, 490, 75, 29);

        jSlider1.setMajorTickSpacing(100);
        jSlider1.setMaximum(60);
        jSlider1.setMinimum(-800);
        jSlider1.setPaintTicks(true);
        jSlider1.setToolTipText("");
        jSlider1.setValue(0);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        add(jSlider1);
        jSlider1.setBounds(280, 340, 380, 38);

        jToggleButton1.setSelected(true);
        jToggleButton1.setText("ON");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        add(jToggleButton1);
        jToggleButton1.setBounds(290, 180, 140, 29);

        mainMenuBackground.setIcon(new javax.swing.ImageIcon("/Users/Nels/Dropbox/maze/Maze/content/images/menuBackground.png")); // NOI18N
        mainMenuBackground.setText("jLabel1");
        add(mainMenuBackground);
        mainMenuBackground.setBounds(0, 0, 945, 751);
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        float value = jSlider1.getValue() / 10;
        parent.game.setVolume(value);
    }//GEN-LAST:event_jSlider1StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        parent.goToMenu();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        System.out.println(jToggleButton1.isSelected());
        if (jToggleButton1.isSelected()) {
            jToggleButton1.setText("ON");
            parent.game.volumeOn();
        } else {
            jToggleButton1.setText("OFF");
            parent.game.volumeOff();
            System.out.println("False");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel mainMenuBackground;
    // End of variables declaration//GEN-END:variables
}
