package Window;

import Utilities.FileReader;
import Utilities.FileWriter;
import java.io.FileNotFoundException;

/**
 *
 * @author Nels
 */
public class OptionPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuPanel
     */
    MainWindow parent;
    public boolean activeGame = false;
    public FileReader reader = new FileReader();
    public FileWriter writer = new FileWriter();
    public int volume;
    public int music;
    public OptionPanel(MainWindow p) throws FileNotFoundException{
        initComponents();
     
        String[] settings = reader.readSettings();        
        
        System.out.println(settings.toString());
        
        int vol = Integer.parseInt(settings[0].split(":")[1]);
        int mus = Integer.parseInt(settings[1].split(":")[1]);
        
        System.out.println("fasdfasdfasdfasdf");
        
        volume = vol;
        this.setFocusable(true);
        parent = p;
        musicSlider.setMaximum(60);
        musicSlider.setMinimum(-800);
        musicSlider.setValue(mus);
        volumeSlider.setMaximum(60);
        volumeSlider.setMinimum(-800);
        volumeSlider.setValue(vol);
        
        System.out.println("ppfaosdasd");
    }
    
    public String buildSettings(){
        
        return "masterVolume:"+volume+"\n"+
               "musicVolume:"+music+"\n";               
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        musicSlider = new javax.swing.JSlider();
        volumeSlider = new javax.swing.JSlider();
        soundToggleButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mainMenuBackground = new javax.swing.JLabel();

        setLayout(null);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(350, 510, 130, 23);

        musicSlider.setMajorTickSpacing(100);
        musicSlider.setMaximum(60);
        musicSlider.setMinimum(-800);
        musicSlider.setPaintTicks(true);
        musicSlider.setToolTipText("");
        musicSlider.setValue(0);
        musicSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                musicSliderStateChanged(evt);
            }
        });
        add(musicSlider);
        musicSlider.setBounds(270, 320, 380, 31);

        volumeSlider.setMajorTickSpacing(100);
        volumeSlider.setMaximum(60);
        volumeSlider.setMinimum(-800);
        volumeSlider.setPaintTicks(true);
        volumeSlider.setToolTipText("");
        volumeSlider.setValue(0);
        volumeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                volumeSliderStateChanged(evt);
            }
        });
        add(volumeSlider);
        volumeSlider.setBounds(270, 400, 380, 31);

        soundToggleButton.setSelected(true);
        soundToggleButton.setText("ON");
        soundToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundToggleButtonActionPerformed(evt);
            }
        });
        add(soundToggleButton);
        soundToggleButton.setBounds(270, 270, 70, 23);

        jLabel1.setText("Sound Volume");
        add(jLabel1);
        jLabel1.setBounds(190, 410, 100, 14);

        jLabel2.setText("Music Volume");
        add(jLabel2);
        jLabel2.setBounds(190, 330, 80, 14);

        jLabel3.setText("Sound");
        add(jLabel3);
        jLabel3.setBounds(190, 270, 70, 20);

        mainMenuBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/menuBackground.png"))); // NOI18N
        mainMenuBackground.setText("jLabel1");
        add(mainMenuBackground);
        mainMenuBackground.setBounds(0, 0, 945, 751);
    }// </editor-fold>//GEN-END:initComponents

    private void volumeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volumeSliderStateChanged
       volume = volumeSlider.getValue();
       writer.writeSettings(buildSettings());
       System.out.println(volumeSlider.getValue());
       
    }//GEN-LAST:event_volumeSliderStateChanged

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        parent.goToMenu();
        
        if(parent.game != null){
            parent.game.setVolume();
            parent.game.setMusicVolume();
        }
        else{
            System.out.println("No game!");
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void soundToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonActionPerformed
        System.out.println(soundToggleButton.isSelected());
        if (soundToggleButton.isSelected()) {
            soundToggleButton.setText("ON");
            parent.game.volumeOn();
        } else {
            soundToggleButton.setText("OFF");
            parent.game.volumeOff();
            System.out.println("False");
        }
    }//GEN-LAST:event_soundToggleButtonActionPerformed

    private void musicSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_musicSliderStateChanged
       music = musicSlider.getValue();
       writer.writeSettings(buildSettings());
       System.out.println(musicSlider.getValue());
    }//GEN-LAST:event_musicSliderStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel mainMenuBackground;
    private javax.swing.JSlider musicSlider;
    private javax.swing.JToggleButton soundToggleButton;
    private javax.swing.JSlider volumeSlider;
    // End of variables declaration//GEN-END:variables
}
